### ISSUE TITLE
Confusing: After I receive bitcoin, the Send tab still implies I don't have any bitcoin

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4855]
_From @bitjson on October 18, 2016 23:52_

I can clearly see the transaction in my wallet, but the send view still looks like this:
![screen shot 2016-10-18 at 7 50 11 pm](https://cloud.githubusercontent.com/assets/904007/19500526/1c777ce2-956c-11e6-9085-77a2fdbd4607.png)

The issue is that the transaction is still confirming, and by default, the wallet does not `Use Unconfirmed Funds`:

![screen shot 2016-10-18 at 7 50 50 pm](https://cloud.githubusercontent.com/assets/904007/19500536/34b817a8-956c-11e6-9059-1f328b5bd24c.png)

_Copied from original issue: bitpay/bitpay-wallet#572_

**Comment by JDonadio** [comment]
_From @bitjson on October 18, 2016 23:54_

What's better, enabling `Use Unconfirmed Funds` by default, or explaining to the user that they need to wait an estimated 20(?) minutes before doing anything (or to enable the setting in `Advanced Settings`)?

Thoughts? @matiu @gasteve @ajp8164 @cmgustavo

**Comment by ajp8164** [comment]
Changing the default setting value just buries the issue - it may come back as support issues for explanation.  

Perhaps we should come up with a way to show unconfirmed funds in the activity list; like post it as it would appear when confirmed but grey it out or dim/mute the colors and add the text "confirming..."

**Comment by JDonadio** [comment]
Done

**Comment by casvanick** [comment]
Hi JDonadio,
I've similar case like yours. 
I would like to stick it to default settings by not enabling the "Use Unconfirmed Funds" and obviously the Send option is still not working for me.
Do you mind shed me some lights, totally new here.

Thanks.
