### ISSUE TITLE
Bought $200 worth of Bitcoin from coinbase but can not see them in copay wallet

### ISSUE THREAD

**Issue by shrkl** [bitpay/copay#6189]

**Comment by JDonadio** [comment]
Hi @shrkl, sorry about that... we found the issue and was fixed already. We are releasing a new version today so probably will be available in a couple of hours or maybe tomorrow on the stores.

**Comment by JDonadio** [comment]
@shrkl can you tell me if you can see now the tx?

**Comment by shrkl** [comment]
I have cleared cache and it still shows no transactions
The Coinbase wallet shows the purchases
IL

**Comment by JDonadio** [comment]
For some reason (probably the fee) your transaction wasn't sent from your Coinbase account to your Copay wallet. I suggest you to contact to the Coinbase support team and ask them for that details.

In addition, can you tell me if your wallet shows any error or simply the tx isn't there?

Thanks in advance

**Comment by cmgustavo** [comment]
If your Coinbase Wallet shows the transaction as confirmed, the bitcoins you bought are there in Coinbase. Please, confirm if your Coinbase wallet have the bitcoins that you bought.

Then in Copay side, could you check if there is an error in the transaction inside the "Coinbase" section? Some times Coinbase could have trouble while trying to send bitcoin to Copay (it 's a Coinbase issue, not Copay).

Thanks.

**Comment by shrkl** [comment]
Its has nothing there - no errors
IL

**Comment by shrkl** [comment]
Confirmed, its all there in coin base, and there is nothing no errors in "coin base" section
IL

**Comment by JDonadio** [comment]
Sorry for the delay. We are working in a improvement to avoid this cases, will be ok for the next release.

**Comment by JDonadio** [comment]
Can you check it again with the latest version?

**Comment by shrkl** [comment]
I just got in.
My Personal Wallet is empty, but if I go through setting it lets me to get into the coinbase and I see my BTC there.
For some reason is not getting into Copay Wallet
IL

**Comment by goferit** [comment]
Same here, two-factor error in bitpay, funds in Coinbase, purchase made through bitpay. Desktop Mac (topmost dmg in your list, 80-some mb, you have two, the other 70-some mb).

**Comment by JDonadio** [comment]
2FA is not supported in Copay. In order to use the service without problem you must disable the 2FA from your Coinbase account.

**Comment by JDonadio** [comment]
Already fixed in the latest version and will work for **new** purchases. 
If you run into this error again please keep us posted. 

Regards.-

**Comment by goferit** [comment]
Request the 2FA issue (if not already addressed) be addressed in the help docs for future users.

**Comment by goferit** [comment]
And, not seeing a way to enable/ disable from Coinbase, and without having to spend to verify, is this (screenshot) the fix?

![image](https://user-images.githubusercontent.com/8900109/27902862-4420afb4-6205-11e7-9f30-8fcc2b1fa5ad.png)

**Comment by spider-man13** [comment]
**JDonadio**, the Google Chrome App has not been updated yet (v3.6.2) and the issue has not been solved since I still have the error message "Two-step verification code required to complete this request. Re-play the request with CB-2FA-Token header".

I have tried to resend my BTC from the coinbase website to my Copay wallet address, and it will not let me neither. It says that "you have not enough funds, try with a smaller amount" but the BTC are shown in coinbase so I have the funds because they were never transferred to Copay. It seems like they are locked because of Copay.

So I am not going to make a **new** purchase if I still have not received (and I can not neither send from coinbase) my existing BTC. Please, let us know how we can get our BTC in our Copay wallets. Thanks!

**Comment by JDonadio** [comment]
2FA is not supported. You must to disable it from your Coinbase account.
